language: ruby
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  app: rocky-castle-27614
  api_key:
    secure: j05W1nSeLTNEmDqA3Vquhm11SZyEDV/352mYdUbW0B8TU+CE0uZLD0i2xXm+ph0vyKzSEVeSF1QCSdTIC/57wa+F3YzKYCO8KOHk4SVRkvdnJMnn+wD+DpyIMbmmZ7fqumBmW2biBUEjSb1TlniQ47b8eKAL6vCxnW2tTq31O4p/pkdheHk9cKcj+oLb9r9HWx+43oSzZvsR06rokZ8Qusq++Aoc5UUjk/yUmbEWGVbFYoCpTC2FTteaSQVM+FypX/MCpOZdWgrEUkILud/G4voynX6isbdFREmheaTJHJD+MyMOHTtOBA5sF2N5S3e6Y7gI9o5h2wSeSdVXBXgZZM0DKjJPzn1Rd6Gojf/89sp47MxIKFwkHpkk2eK2k8UQGrPkGLnFBrJZ3sDOBWuhnwKJNmOhmN0/EbSz6yhMIj36TT1F9j/Dfce3kCf0tnUd3SW3mGtjgKRzPvbhyAsoU/8+tIUoa+B2dFvQornROeMsLi/pKnKCGeWtbRPR+dY0sGQTFNJljMto0IwFLrBB1QGEpi+pabpPD/wwpvEaCFsQGEFlXLUvOYanuSKsNJTUAI4baXffNldkAg4GV7vae42jObEc2BSJQdvD8QTEpcBtUag5qkRe9uURGw3xrUqrEkPY+6KFMS4+14L5KW5ahxjTcvZOfaytH5UtNhgZtdw=
  run:
    - "rails db:migrate"
